baseurl = "https://yoxxa.github.io/"
title = "yoxxa"
copyright = "Copyright &copy; 2024 - yoxxa"
canonifyurls = true
theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = false
pygmentsCodeFences = true

#disqusShortname = "myShortName"

# Note: to disable a social network icon delete or comment out the corresponding line
[author]
    name = "yoxxa"
    email = "theyoxxa@protonmail.com"
    github = "yoxxa"
    #gitlab = "username"
    #linkedin = "username"
    #facebook = "username"
    #twitter = "yoxxa"
    #instagram = "username"
    #stackoverflow = "username"
    #youtube = "user/username" # or channel/channelname
    #devto = "username"

[params]
    tagline = "Computing. Philosophy. Maths."
    description = "The digital garden of an internet user named yoxxa."
    #images = [""] #This is used for opengraph/twitter cards.
    customCSS = []  #Optional Customised CSS
    #favicon = ""
    #utterancesRepo = "username/repository"
    #utterancesIssueTerm = "pathname"
    #homepageLength = 10
    #commentAutoload = true  #This mean reader don't need click, disqus comment autoload
    #mathjax = true #Enable display of mathematics using mathjax (LaTeX syntax)
    #katex = true #Enable display of mathematics using katex (Faster LaTeX rendering)
    #google_fonts = ["Staatliches"] # Adds additional google fonts
    #disableDarkModeCSS = false # disables css style for users using dark-mode

# uncomment to enable the Tags link on the main toolbar
#  [[menu.main]]
#    identifier = "tags"
#    name = "Tags"
#    url = "/tags"
#    weight = 1

# uncomment to enable the Categories link on the main toolbar
#  [[menu.main]]
#    identifier = "categories"
#    name = "Categories"
#    url = "/categories"
#    weight = 1
